export const APP_INIT = "APP_INIT";
export const LOADING_ICON_STATUS_UPDATE = "LOADING_ICON_STATUS_UPDATE";
export const OPTION_DATA_UPDATE = "OPTION_DATA_UPDATE";
export const USER_INPUT_CHANGE = "USER_INPUT_CHANGE";
export const OPTION_SELECTED = "OPTION_SELECTED";
